---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Deploy Elastic Stack
      cloudformation:
        state: present
        stack_name: buildkite-kubernetes-tutorial-elastic-stack
        region: ap-southeast-1
        profile: slashdeploy
        template_url: "https://s3.amazonaws.com/buildkite-aws-stack/v4.3.1/aws-stack.yml"
        template_parameters:
          ManagedPolicyARN: arn:aws:iam::aws:policy/PowerUserAccess
          InstanceType: t2.micro
          BuildkiteAgentToken: "3ba66f4248a4a3062b5060cdae6292c7873c48f48e4245e295"
          KeyName: dev-box
          MinSize: 0
          MaxSize: 1
      register: cf

    - name: Upload private Key
      aws_s3:
        mode: put
        bucket: "{{ cf.stack_outputs.ManagedSecretsBucket }}"
        object: /private_ssh_key
        permission: private
        encryption_mode: aws:kms
        src: .private/id_rsa_buildkite
        profile: slashdeploy

