steps:
  - label: ':hammer: Test'
    command: script/buildkite/test
    agents:
      cloud: gcp

  - wait

  - label: ':docker: Push'
    command: script/buildkite/push
    env:
      DOCKER_IMAGE: "asia.gcr.io/buildkite-kubernetes-tutorial/app:${BUILDKITE_BUILD_NUMBER}"
    agents:
      cloud: gcp
