steps:
  - label: ':hammer: Test'
    command: script/buildkite/test
    agents:
      cloud: gcp

  - label: ':docker: Push'
    command: 'script/buildkite/push "asia.gcr.io/buildkite-kubernetes-tutorial/app:${BUILDKITE_BUILD_NUMBER}"'
    agents:
      cloud: gcp
