steps:
  - label: ':hammer: Test'
    command: script/buildkite/test
    agents:
      cloud: gcp

  - wait

  - label: ':docker: Push'
    command: script/buildkite/push
    agents:
      cloud: gcp

  - label: ':rocket: Deploy'
    command: script/buildkite/deploy
    concurrency: 1
    concurrency_group: deploy/tutorial
    agents:
      cloud: gcp
