#!/usr/bin/env bash

set -eu

export DOCKER_IMAGE_NAME="asia.gcr.io/buildkite-kubernetes-tutorial/app:${BUILDKITE_BUILD_NUMBER}"

echo '--- :gcloud: Setup'

gcloud config set project 'buildkite-kubernetes-tutorial'
gcloud config set compute/zone 'asia-southeast1-a'
gcloud config set compute/region 'asia-southeast1'

gcloud container clusters get-credentials buildkite-tutorial

set +eu

# mkdir -p "${HOME}/bin"
#
# curl -sSL -o "${HOME}/bin/kubectl" \
# 	https://amazon-eks.s3-us-west-2.amazonaws.com/1.11.9/2019-03-27/bin/linux/amd64/kubectl
# curl -sSL -o "${HOME}/bin/aws-iam-authenticator" \
# 	https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.7/2019-03-27/bin/linux/amd64/aws-iam-authenticator
# curl -sSL -o "${HOME}/bin/kops" \
# 	https://github.com/kubernetes/kops/releases/download/1.11.1/kops-linux-amd64
#
# chmod +x "${HOME}/bin/kubectl"
# chmod +x "${HOME}/bin/aws-iam-authenticator"
# chmod +x "${HOME}/bin/kops"
#
# export "PATH=${HOME}/bin:${PATH}"
#
# echo '$ kubectl --version'
# kubectl version --client
#
# echo '$ aws-iamauthenticator version'
# aws-iam-authenticator version
#
# echo '$ kops version'
# kops version
#
# set +eu
