#!/usr/bin/env bash

set -eu

local scratch="$(mktemp -d)"

curl -sSL -o "${scratch}/kubectl" \
	https://amazon-eks.s3-us-west-2.amazonaws.com/1.11.9/2019-03-27/bin/linux/amd64/kubectl
curl -sSL -o "${scratch}/aws-iam-authenticator" \
	https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.7/2019-03-27/bin/linux/amd64/aws-iam-authenticator

export "PATH=${scratch}:${PATH}"

kubectl version --client
aws-iam-authenticator --version

set +eu
