#!/usr/bin/env bash

set -eu

mkdir -p "${HOME}/bin"

curl -sSL -o "${HOME}/bin/kubectl" \
	https://amazon-eks.s3-us-west-2.amazonaws.com/1.11.9/2019-03-27/bin/linux/amd64/kubectl
curl -sSL -o "${HOME}/bin/aws-iam-authenticator" \
	https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.7/2019-03-27/bin/linux/amd64/aws-iam-authenticator

chmod +x "${HOME}/bin/kubectl"
chmod +x "${HOME}/bin/aws-iam-authenticator"

export "PATH=${HOME}/bin:${PATH}"

echo '$ kubectl --version'
kubectl version --client

echo '$ aws-iamauthenticator version'
aws-iam-authenticator version

echo ':kubernetes: Connecting'

aws eks \
	--region ap-south-1 \
	update-kubeconfig \
	--name buildkite-tutorial

set +eu
