#!/usr/bin/env bash

set -eu

mkdir -p "${HOME}/bin"

curl -sSL -o "${HOME}/bin/kubectl" \
	https://amazon-eks.s3-us-west-2.amazonaws.com/1.11.9/2019-03-27/bin/linux/amd64/kubectl
curl -sSL -o "${HOME}/bin/aws-iam-authenticator" \
	https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.7/2019-03-27/bin/linux/amd64/aws-iam-authenticator

export "PATH=${HOME}/bin:${PATH}"

kubectl version --client
aws-iam-authenticator --version

set +eu
