#!/usr/bin/env bash

set -euo pipefail

main() {
	echo '--- :docker: Pushing'

	docker-compose build app
	docker tag $(docker-compose images -q) "${DOCKER_IMAGE_NAME}"
	docker push "${DOCKER_IMAGE_NAME}"
}

main "$@"
