#!/usr/bin/env bash

set -euo pipefail

main() {
	echo "--- :docker: Pushing ${DOCKER_IMAGE}"

	docker-compose build app
	docker tag buildkite/kubernetes-tutorial:latest "${DOCKER_IMAGE}"
	docker push "${DOCKER_IMAGE}"
}

main "$@"
