#!/usr/bin/env bash

set -euo pipefail

main() {
	echo ':kubernetes: Connecting'

	aws eks \
		--region ap-southeast-1 \
		update-kubeconfig \
		--name buildkite-tutorial

	echo 'Checking kubectl connection'

	kubectl get services
}

main "$@"
