#!/usr/bin/env bash

set -euo pipefail

main() {
	echo 'Loading kubeconfig from kops'

  kops export kubecfg buildkite-k8s.slashdeploy.com

	echo 'Checking cluster access'

	kubectl get services
}

main "$@"
