#!/usr/bin/env bash

set -euo pipefail

main() {
	echo '--- :docker: Setup'

	docker-compose up --build -d app

	echo '--- :zzz: waiting'

	sleep 2

	echo '--- Testing'

	curl -s "$(docker-compose port app 3000)"

	echo 'OK'

}

main "$@"
